name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0

        with:
          project_id: ${{ secrets.PROJECT_ID }}
          version: master
          credentials: ${{secrets.GCP_CREDENTIAL}}
          flags: --no-cache
          deliverables: app.yaml
