export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
export const UPDATE_SEARCH_PARAMS = "UPDATE_SEARCH_PARAMS";
export const UPDATE_SEARCH_HISTORY = "UPDATE_SEARCH_HISTORY";
export const DELETE_HISTORY_BY_INDEX = "DELETE_HISTORY_BY_INDEX";