name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google App Engine
        uses: google-github-actions/deploy-appengine@v1.1.0

        with:
          deliverables: app.yaml
          version: v1
          flags: --no-cache
          # project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
